=== Dark90lab/.NET---projects/xml-xsd _Pastures_Serialization/PasturesInterface/bin/Debug/netcoreapp3.1/Pastures.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    targetNamespace="http://tempuri.org/Pastures.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/Pastures.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:simpleType name="pastureFenceType">
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="short"/>
          <xs:enumeration value="tall"/>
          <xs:enumeration value="none"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="xs:decimal">
          <xs:fractionDigits value="2" />
          <xs:minExclusive value="0.00"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>
  
  <xs:simpleType name="pastureID">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z]{2}[0-9]{1}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="pastureNameType">
    <xs:restriction base="xs:string">
      <xs:pattern value="^[A-Z][a-z]*( [A-Z][a-z]*)*$"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ageType">
    <xs:restriction base="xs:int">
      <xs:minExclusive value="6"/>
    </xs:restriction>
  </xs:simpleType>
  
  
  <xs:complexType name="pastureType">
    <xs:attribute name="area" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="fence" type="pastureFenceType" use="required"/>
    <xs:attribute name="id" type="pastureID" use="required"/>
    <xs:attribute name="name" type="pastureNameType" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="pasturesType">
    <xs:sequence>
      <xs:element name="pasture" type="pastureType" minOccurs="1" maxOccurs="11"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tatooType">
      <xs:attribute  name="picture" type="xs:string"/>
  </xs:complexType>

  <xs:simpleType name="massType">
    <xs:restriction base="xs:decimal">
      <xs:maxExclusive value="1000"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="centaurType">
    <xs:sequence>
      <xs:element name="tatoo" type="tatooType" minOccurs="0" maxOccurs="3"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="age" type="ageType" use="required"/>
    <xs:attribute name="id" type="xs:int" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="minotaurType">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="age" type="ageType" use="required"/>
    <xs:attribute name="id" type="xs:int" use="required"/>
    <xs:attribute name="mass" type="massType" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="creaturesType">
    <xs:sequence>
      <xs:element name="centaur" type="centaurType" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="minotaur" type="minotaurType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="pastureReferenceType">
    <xs:attribute  name="id" type="pastureID" use="required"/>
  </xs:complexType>

  <xs:complexType name="creatureReferenceType">
    <xs:attribute  name="id" type="xs:int" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="plantsType">
    <xs:sequence>
      <xs:element name="plant" type="plantType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="plantType">
    <xs:sequence>
      <xs:element name="pasture" type="pastureReferenceType" minOccurs="2" maxOccurs="unbounded"/>
      <xs:element name="creature" type="creatureReferenceType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:element name="spotkania">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pastures" type="pasturesType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="creatures" type="creaturesType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="plants" type="plantsType" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:key name="pastureKey">
      <xs:selector xpath="pasture"/>
      <xs:field xpath="@id"/>
    </xs:key>
    
    <xs:keyref name="pastureRef" refer="pastureKey">
      <xs:selector xpath="spotkania/plants/pasture"/>
      <xs:field xpath="@id"/>
    </xs:keyref>
    
    <xs:key name="creatureKey">
      <xs:selector xpath="centaur|minotaur"/>
      <xs:field xpath="@id"/>
    </xs:key>

    <xs:keyref name="creatureKeyRef" refer="creatureKey">
      <xs:selector xpath="spotkania/plants/creature"/>
      <xs:field xpath="@id"/>
    </xs:keyref>
    
  </xs:element> 
</xs:schema>

=== Dark90lab/.NET---projects/xml-xsd _Pastures_Serialization/PasturesInterface/bin/Debug/netcoreapp3.1/Pastures-xml.xml
<?xml version="1.0" encoding="utf-8"?>      
<spotkania
  xmlns="http://tempuri.org/Pastures.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://tempuri.org/Pastures.xsd Pastures.xsd">
<pastures>
    <pasture area="20" fence="short" id="tr2" name="Quiet Meadow"/>
    <pasture area="31" fence="4.00" id="mr2" name="Green Bright Flatland"/>
    <pasture area="99" fence="tall" id="bw4" name="Wasteland"/>
  </pastures>
  <creatures>
    <centaur name="Larry" age="23" id="1">
      <tatoo picture="butterfly"/>
      <tatoo picture="pidgeon"/>
      <tatoo picture="minotaur"/>
    </centaur>
    <centaur name="Sonny" age="25" id="2"/>
    <minotaur name="Roger" age="15" id="4" mass="989"/>
  </creatures>
  <plants>
    <plant name="plant1">
      <pasture id="tr2"/>
      <pasture id="mr2"/>
      <creature id="2"/>
      <creature id="1"/>
    </plant>
    <plant name="plant2">
      <pasture id="bw4"/>
      <pasture id="mr2"/>
      <creature id="4"/>
      <creature id="1"/>
    </plant>
  </plants>
</spotkania>
